### PR TITLE
Updated for Webpack 3, and fixed bug of SVGSVGElement

### PR DESCRIPTION
**Pull request by mohammed-io**
Hello, frappe team,

I updated all packages to the latest versions, with Webpack 3 configuration ofc.
There was some issues when the type of the element is SVGSVGElement, now it works without any problem.

Now it's better with npm packages.

Please remember to **update** package.json version when publishing to npm.

Happy coding!
🥇

### CODE REVIEW

**Comment by netchampfaris** [comment]
Why no `dist` folder? I thought libraries are expected to have a dist folder with the latest build for production use.

**Comment by mohammed-io** [comment]
Hey @netchampfaris, the `dist` folder will be created when running command `npm run build`
see React or jQuery for example, they have either an empty dist or no dist at all.
But some little change, the output file will be `dist/index.js` not `dist/frappe-gantt.js` as was before, you can say, it's more NPM friendly.

**Comment by paullbn** [comment]
Hello Frappe Team!

Will this PR be merged? :innocent:

**Comment by coulson84** [comment]
Would be great if this feature could be merged..... it's been a while.

**Comment by netchampfaris** [comment]
The latest version uses rollup as the build tool.

**Pull request closed without merging**
