### PR TITLE
Add hour view mode

### PR DESCRIPTION
**Pull request by anto-christo**
This PR adds an option to view tasks in hourly mode.
Just add the hour value after the date and set the `view_mode` option to `Hour`.

**Example**
```
<script>
        var tasks = [
            {
                start: '2018-10-01 00',
                end: '2018-10-01 05',
                name: 'Redesign website',
                id: "Task 0",
                progress: 20
            },
            {
                start: '2018-10-01 01',
                end: '2018-10-01 08',
                name: 'Write new content',
                id: "Task 1",
                progress: 5,
                dependencies: 'Task 0'
            },
            {
                start: '2018-10-01 07',
                end: '2018-10-01 18',
                name: 'Apply new styles',
                id: "Task 2",
                progress: 10,
                dependencies: 'Task 1'
            }
        ]
        var gantt_chart = new Gantt(".gantt-target", tasks, {
            view_mode: 'Hour',
            language: 'en'
        });
    </script>
```

**Output**
hour-view

**Note**
The chart may take a long time to load or the page may crash if `Hour` view mode is used with long tasks that span over multiple years.

@netchampfaris kindly review.

### CODE REVIEW

**Comment by MaartenMostert** [comment]
Hello can someone explain how to use this version with the Hour View. The latest vailable version doesn't include it ?
Thanks, 
Maarten,

**Comment by WayneExall** [comment]
Hi Maarten
Did you figure out how to use this version? I would also like to know.
Regards,
Wayne

**Comment by rhayart** [comment]
I have tested the hour view mode and it seems to work with simple data ;)

**Comment by mgaitan09** [comment]
this is awesome, any hope getting it in? I'll put in some work for this if needed

**Comment by PanktiDoshi95** [comment]
Hello can someone explain how to use this version with the Hour View. The latest vailable version doesn't include it ?
Thanks,
Pankti,

**Comment by rhayart** [comment]
The PR is not merged into the master at the moment.
I had to fork the project to merged the PR and use this feature.

**Review by hasanbasriayasli — APPROVED** [review]

**Comment by dhyunk** [comment]
Is anyone downloaded this version of library?
How do I get this version?

**Review by s-aga-r — CHANGES_REQUESTED** [review]
@anto-christo please resolve conflicts.

**Comment by safwansamsudeen** [comment]
Thank you very much ;). I haven't merged the PR directly as it's old and conflicts have grown, but have used your code to make the commit.

**Pull request closed without merging**
