### PR TITLE
New features implemented

### PR DESCRIPTION
**Pull request by 7-AM**
Features: 
1) Require and module exports integration on npm projects error fixed. Useful for AngularJs modular architecture
2) Thumbnail support for label display on each Bar element
3) Label move on X axis when user scroll so they will always remember the name of the task
4) Thumbnail round mask
5) Sticker Date Header when scrolling on Y axis 
6) Boolean option to actions (resize|drag|progress). Static Gantt feature

### CODE REVIEW

**Comment by chathuraa** [comment]
Hi, Im interested in the sticky/fixed header. Can you please guide me how you implemented that?
thanks,
Chat

**Comment by jcjobin** [comment]
Can this all be merged into master? Is it currently? I like the sticky header addition!

**Comment by RahulShahUI** [comment]
can we disable the event drag?

**Review by zajinx — APPROVED** [review]

**Review by s-aga-r — CHANGES_REQUESTED** [review]
@7-AM please resolve conflicts.

**Comment by safwansamsudeen** [comment]
Brilliant work - thank you so much!

This has been integrated in #393.

@7-AM do you know of a way to have a background behind the header fixed? I imagine one could draw a rectangle just before drawing the dates - but if you have a working solution, please share.

Apologies for the delay here - and thanks again.

**Pull request closed without merging**
