### PR TITLE
Pre v1 Cleanup

### PR DESCRIPTION
**Pull request by safwansamsudeen**
We're fixing all the issues since May before we release v1 of Frappe Gantt onto npm.

### CODE REVIEW

**Comment by MercurialUroboros** [comment]
Hi - This MR has some issues.

Namely:
image
image

This one not an error from the MR but just redundancy.

image

**Comment by safwansamsudeen** [comment]
@MercurialUroboros feel free to open a PR!

**Comment by MercurialUroboros** [comment]
> @MercurialUroboros feel free to open a PR!

I don't think I can, i tried to push a branch, but I don't have permissions, sorry i'm new to opensource per se.

**Comment by MercurialUroboros** [comment]
> @MercurialUroboros So you should fork this repo, push a branch to _your_ fork (which is a clone of this repo), and then open a PR onto this one. The team will review it and then merge it.

https://github.com/frappe/gantt/pull/475/files Here you have!

**Pull request merged**
