### PR TITLE
feat: add the es export path

### PR DESCRIPTION
**Pull request by xiaweixuan**
I tried to reference it in my project, but got an error because the export file for es is not declared in package.json

### CODE REVIEW

**Comment by zewa666** [comment]
can confirm, this fixes integration of the gantt in a vite based application.

**Comment by zewa666** [comment]
does pretty much the same, except this one also adds an alias export /style next to /*. yours on the other hand takes care of the tree shaking.

**Comment by safwansamsudeen** [comment]
@zewa666 so what's the use of the alias? I currently pushed this:

```js
"exports": {
    ".": {
        "require": "./dist/frappe-gantt.umd.js",
        "import": "./dist/frappe-gantt.es.js",
        "style": "./dist/frappe-gantt.css"
    }
}
```

**Comment by zewa666** [comment]
wheter you `import * from "yourpackage"` or `import myStyles from "yourpackage/styles"`

**Comment by safwansamsudeen** [comment]
Closing as we've added this.

**Pull request closed without merging**
