### PR TITLE
feat : package upgrade and add resource area

### PR DESCRIPTION
**Pull request by lahuman**
update module & use way rollup uglify

### CODE REVIEW

**Comment by lahuman** [comment]
I added a resource area.

Look like this.

image

However, it doesn't support left pinning yet.

**Comment by cfontes** [comment]
This looks great, any hope of merging it?

**Review by s-aga-r — CHANGES_REQUESTED** [review]
@lahuman please resolve conflicts.

**Comment by safwansamsudeen** [comment]
We're using #286 instead.

**Pull request closed without merging**
