### PR TITLE
new feature for customize

### PR DESCRIPTION
**Pull request by hustcc**
This pr contains below:

1. add **three attributes** for customize
2. update **index.html** for new feature
3. update **readme**
4. modify some code **indent**
5. update webpack.config.js (`let`) for old nodejs version

#11 solved. Review is needed. Compatible with older versions.

### CODE REVIEW

**Comment by netchampfaris** [comment]
@hustcc 
Hi, thanks for your PR.
How about this. We just give a single option of `custom_class` and then user can override any part of the task.
For e.g
```
// in js
{
	start: start,
	end: end,
	name: name,
	id: "Task 1",
	progress: 42,
	custom_class: "bar-milestone"
}

// in css
.bar-milestone .bar {
	fill: #fff;
}
.bar-milestone .bar-progress {
	fill: #ff0;
}
.bar-milestone .bar-label {
	fill: #f0f;
}
```

**Comment by hustcc** [comment]
That will be perfect, better than this pr.

**Comment by hustcc** [comment]
Done here: https://github.com/frappe/gantt/pull/12/commits/75008011ebffeebfe2a6d7665b379d63a2d9740b

You can just push your own code, ignore this pr, and release a new version. :laughing:

**Comment by netchampfaris** [comment]
Enhanced your PR here https://github.com/frappe/gantt/pull/14 and merged. Thanks for your contribution

**Pull request closed without merging**
